import type { RiskStateData, BriefMock, PersonaMock, StudioIssue } from './types';

export const riskStates: Record<'aman' | 'pantau' | 'kritis', RiskStateData> = {
  aman: {
    statusText: 'Situasi Aman',
    statusDesc: 'Tidak ada isu kritis yang terdeteksi. Pantau tetap diperlukan.',
    ewScore: 18,
    ewLevel: 'Aman',
    aiSummary: 'Situasi narasi berada dalam kondisi stabil pagi ini. Sentimen publik terhadap Bapak Joko mencatat kenaikan tipis +3% dibanding kemarin, didorong respons positif atas pernyataan soal ketahanan pangan. Volume percakapan di TikTok meningkat 12% namun tonalitas tetap konstruktif. Tidak ada isu kritis yang perlu penanganan segera.',
    issues: [
      { id: '1', title: 'Program Makan Bergizi Gratis', platform: 'Twitter/X', mentions: 42300, sentiment: 'positif', direction: 'up', level: 'Aman', actionable: false },
      { id: '2', title: 'Infrastruktur Desa Digital', platform: 'TikTok', mentions: 28900, sentiment: 'positif', direction: 'up', level: 'Aman', actionable: false },
      { id: '3', title: 'Harga Kebutuhan Pokok', platform: 'Instagram', mentions: 19400, sentiment: 'netral', direction: 'flat', level: 'Pantau', actionable: true },
      { id: '4', title: 'Jadwal Kunjungan Daerah', platform: 'News', mentions: 11200, sentiment: 'netral', direction: 'flat', level: 'Aman', actionable: false },
    ],
    narratives: [
      { id: '1', tag: 'POPULIS', velocity: '+8% / jam', quote: '"Pemimpin yang turun langsung ke lapangan membuktikan kepedulian nyata."', fill: 72, subtitle: 'Naratif organik dari konstituen Jawa Tengah' },
      { id: '2', tag: 'EKONOMI', velocity: '+3% / jam', quote: '"Kebijakan subsidi tepat sasaran mulai dirasakan manfaatnya oleh masyarakat kecil."', fill: 54, subtitle: 'Beredar di grup WhatsApp komunitas pedagang' },
      { id: '3', tag: 'INFRASTRUKTUR', velocity: '+1% / jam', quote: '"Jalan desa yang diperbaiki tahun ini menjadi bukti pembangunan yang merata."', fill: 38, subtitle: 'Video viral di TikTok, 2.3 juta penonton' },
    ],
    sentiment: { positif: 74, netral: 18, negatif: 8 },
    sentimentTrend: [58, 62, 65, 61, 68, 71, 74],
    keywords: { nama: '48.2k', partai: '12.1k', isuUtama: 'ketahanan pangan', oposisi: '4.2k' },
    competitors: [
      { name: 'Anies B.', delta: -2, direction: 'down' },
      { name: 'Ganjar P.', delta: +1, direction: 'up' },
      { name: 'Prabowo S.', delta: 0, direction: 'flat' },
    ],
    influencers: [
      { name: 'Dr. Rizal M.', reach: '2.1M', stance: 'Friendly', color: '#2D6A47' },
      { name: 'Kang Deni', reach: '890K', stance: 'Netral', color: '#B89455' },
      { name: 'Prof. Sari W.', reach: '650K', stance: 'Friendly', color: '#2D6A47' },
    ],
    platforms: [
      { name: 'TikTok', fill: 78, value: '78%' },
      { name: 'Twitter/X', fill: 62, value: '62%' },
      { name: 'Instagram', fill: 55, value: '55%' },
      { name: 'News', fill: 41, value: '41%' },
    ],
    askSuggestions: [
      'Apa yang mendorong kenaikan sentimen hari ini?',
      'Narasi mana yang paling cepat menyebar?',
      'Platform mana yang paling aktif bicara soal saya?',
      'Rekomendasikan aksi komunikasi untuk mempertahankan tren positif ini.',
    ],
    askResponse: 'Sentimen positif hari ini terutama didorong oleh konten video kunjungan lapangan yang viral di TikTok dengan 2.3 juta penayangan. Narasi "pemimpin yang turun ke rakyat" beredar organik tanpa perlu amplifikasi buatan. Rekomendasi: pertahankan jadwal kunjungan daerah dan pastikan tim dokumentasi menghasilkan konten autentik yang dapat dibagikan.',
  },

  pantau: {
    statusText: 'Pantau Aktif',
    statusDesc: 'Beberapa isu memerlukan perhatian. Siapkan respons jika eskalasi.',
    ewScore: 54,
    ewLevel: 'Pantau',
    aiSummary: 'Terdapat dua isu yang memerlukan pemantauan intensif: kontroversi dana aspirasi DPR yang mulai menarik perhatian media nasional, dan narasi soal reshuffle kabinet yang beredar di lingkar elite. Volume percakapan negatif meningkat 23% dalam 4 jam terakhir. Rekomendasikan kesiapan draft respons untuk scenario terburuk.',
    issues: [
      { id: '1', title: 'Dana Aspirasi Kontroversi', platform: 'Twitter/X', mentions: 67800, sentiment: 'negatif', direction: 'down', level: 'Pantau', actionable: true },
      { id: '2', title: 'Isu Reshuffle Kabinet', platform: 'News', mentions: 45200, sentiment: 'campur', direction: 'flat', level: 'Pantau', actionable: true },
      { id: '3', title: 'Subsidi BBM Dipangkas', platform: 'TikTok', mentions: 38900, sentiment: 'negatif', direction: 'down', level: 'Pantau', actionable: true },
      { id: '4', title: 'Kunjungan ke Daerah 3T', platform: 'Instagram', mentions: 22100, sentiment: 'positif', direction: 'up', level: 'Aman', actionable: false },
    ],
    narratives: [
      { id: '1', tag: 'KRITIS', velocity: '+31% / jam', quote: '"Dana aspirasi seharusnya sampai ke rakyat, bukan hilang di tengah jalan."', fill: 68, subtitle: 'Trending di Twitter/X, diinisiasi akun oposisi' },
      { id: '2', tag: 'PANTAU', velocity: '+18% / jam', quote: '"Reshuffle kabinet bukan solusi jika sistemnya tidak berubah."', fill: 45, subtitle: 'Beredar di media online nasional' },
      { id: '3', tag: 'KONTRA', velocity: '+12% / jam', quote: '"Kebijakan BBM menyusahkan rakyat kecil yang sudah susah."', fill: 38, subtitle: 'Viral di TikTok dari akun influencer ekonomi' },
    ],
    sentiment: { positif: 48, netral: 28, negatif: 24 },
    sentimentTrend: [71, 68, 65, 58, 54, 50, 48],
    keywords: { nama: '82.1k', partai: '31.4k', isuUtama: 'dana aspirasi', oposisi: '19.8k' },
    competitors: [
      { name: 'Anies B.', delta: +4, direction: 'up' },
      { name: 'Ganjar P.', delta: +2, direction: 'up' },
      { name: 'Prabowo S.', delta: -1, direction: 'down' },
    ],
    influencers: [
      { name: 'Rocky G.', reach: '3.8M', stance: 'Pantau', color: '#CB102E' },
      { name: 'Budiman S.', reach: '1.2M', stance: 'Netral', color: '#B89455' },
      { name: 'Nikita M.', reach: '4.5M', stance: 'Netral', color: '#B89455' },
    ],
    platforms: [
      { name: 'TikTok', fill: 85, value: '85%' },
      { name: 'Twitter/X', fill: 79, value: '79%' },
      { name: 'Instagram', fill: 61, value: '61%' },
      { name: 'News', fill: 72, value: '72%' },
    ],
    askSuggestions: [
      'Siapa yang pertama kali menyebarkan narasi dana aspirasi ini?',
      'Berapa lama biasanya isu serupa berlangsung sebelum mereda?',
      'Scenario respons mana yang paling aman untuk isu ini?',
      'Apa risiko jika kita memilih diam strategis hari ini?',
    ],
    askResponse: 'Isu dana aspirasi berawal dari akun @watchdog_id yang memposting dokumen tidak terverifikasi pada pukul 03.24 WIB. Dalam 6 jam, konten tersebut direplikasi 2.400 kali. Berdasarkan pola isu serupa (reshuffle 2022, APBN 2021), siklus berita biasanya 36–72 jam sebelum organik mereda. Scenario Netral (02) direkomendasikan: akui keberadaan pertanyaan publik tanpa memberikan detail yang dapat dikapitalisasi oposisi.',
  },

  kritis: {
    statusText: 'Status Kritis',
    statusDesc: 'Isu kritis aktif. Respons segera diperlukan.',
    ewScore: 87,
    ewLevel: 'Kritis',
    aiSummary: 'PERINGATAN KRITIS: Tagar #KebijaksanaanX trending di posisi 1 nasional dengan volume 240.000 cuitan dalam 2 jam. Narasi menyerang langsung integritas pengambilan keputusan. Media nasional mulai meliput. Waktu respons ideal: dalam 90 menit. Response Studio telah menyiapkan tiga draft. Koordinasi dengan tim komunikasi segera diperlukan.',
    issues: [
      { id: '1', title: '#KebijaksanaanX Trending #1', platform: 'Twitter/X', mentions: 240000, sentiment: 'negatif', direction: 'down', level: 'Kritis', actionable: true },
      { id: '2', title: 'Media Nasional Mulai Meliput', platform: 'News', mentions: 89400, sentiment: 'negatif', direction: 'down', level: 'Kritis', actionable: true },
      { id: '3', title: 'Petisi Online Beredar', platform: 'Instagram', mentions: 61200, sentiment: 'negatif', direction: 'down', level: 'Kritis', actionable: true },
      { id: '4', title: 'Tokoh Oposisi Merespons', platform: 'TikTok', mentions: 44800, sentiment: 'negatif', direction: 'down', level: 'Pantau', actionable: true },
    ],
    narratives: [
      { id: '1', tag: 'KRISIS', velocity: '+89% / jam', quote: '"Kebijakan ini dibuat tanpa mendengar suara rakyat — inilah buktinya."', fill: 91, subtitle: 'Trending #1 nasional, diperkuat oleh 12 akun berpengaruh' },
      { id: '2', tag: 'VIRAL', velocity: '+67% / jam', quote: '"Petisi sudah 180.000 tanda tangan dalam 3 jam. Rakyat tidak diam."', fill: 78, subtitle: 'Dari platform change.org, viral di semua platform' },
      { id: '3', tag: 'MEDIA', velocity: '+44% / jam', quote: '"Tiga media nasional sudah konfirmasi akan tayang jam 19.00 WIB."', fill: 65, subtitle: 'Dikonfirmasi jurnalis CNN Indonesia dan Kompas TV' },
    ],
    sentiment: { positif: 18, netral: 14, negatif: 68 },
    sentimentTrend: [65, 58, 48, 38, 28, 22, 18],
    keywords: { nama: '241k', partai: '88k', isuUtama: '#KebijaksanaanX', oposisi: '102k' },
    competitors: [
      { name: 'Anies B.', delta: +12, direction: 'up' },
      { name: 'Ganjar P.', delta: +8, direction: 'up' },
      { name: 'Prabowo S.', delta: +3, direction: 'up' },
    ],
    influencers: [
      { name: 'Refly H.', reach: '5.2M', stance: 'Pantau', color: '#CB102E' },
      { name: 'Ade A.', reach: '2.8M', stance: 'Pantau', color: '#CB102E' },
      { name: 'Ahmad D.', reach: '1.9M', stance: 'Pantau', color: '#CB102E' },
    ],
    platforms: [
      { name: 'TikTok', fill: 94, value: '94%' },
      { name: 'Twitter/X', fill: 97, value: '97%' },
      { name: 'Instagram', fill: 82, value: '82%' },
      { name: 'News', fill: 88, value: '88%' },
    ],
    askSuggestions: [
      'Respons apa yang harus saya buat dalam 90 menit ke depan?',
      'Siapa tokoh netral yang bisa saya ajak bicara untuk meredakan ini?',
      'Bagaimana risiko jika saya merespons vs. memilih diam?',
      'Apa yang harus disampaikan Comms Director ke media nasional sekarang?',
    ],
    askResponse: 'Situasi memerlukan respons dalam 60 menit untuk memotong momentum viral sebelum berita jam 19.00. Rekomendasi: gunakan Scenario 01 Proaktif — buat pernyataan langsung yang mengakui kekhawatiran publik sambil menyajikan fakta yang dapat diverifikasi. Hindari bahasa defensif. Kirim melalui akun resmi Twitter/X terlebih dahulu, diikuti siaran pers formal 30 menit kemudian. Tim perlu memastikan tidak ada pernyataan bertentangan dari pejabat lain.',
  },
};

export const briefMock: BriefMock = {
  number: 142,
  date: 'Kamis, 22 Mei 2026',
  popularity: '+12%',
  popularityNote: 'Didorong oleh respons positif atas kunjungan ke Sulawesi Tenggara dan video program MBG yang viral.',
  topics: [
    { name: 'Subsidi BBM', sentiment: 'positif', sentimentPct: 72, mentions: 48200, direction: 'up' },
    { name: 'Reshuffle Kabinet', sentiment: 'netral', sentimentPct: 58, mentions: 31500, direction: 'flat' },
    { name: 'Kebijakan IKN', sentiment: 'negatif', sentimentPct: 34, mentions: 22000, direction: 'down' },
    { name: 'Harga Beras', sentiment: 'campur', sentimentPct: 41, mentions: 18900, direction: 'flat' },
  ],
  actions: [
    'Publikasikan pernyataan singkat soal stabilitas harga beras sebelum pukul 09.00',
    'Tinjau draft wawancara Kompas TV — hindari topik reshuffle hingga ada keputusan resmi',
    'Approve konten TikTok seri "Kunjungan Rakyat" yang sudah disiapkan tim',
  ],
  regionAlert: '3 wilayah perlu perhatian: Sulawesi Selatan (+38% volume negatif), Kalimantan Timur (isu IKN meningkat), Jawa Barat (harga beras jadi topik utama).',
  quote: '"Sebelum bicara, mendengar." — Pepatah diplomasi yang relevan dengan situasi komunikasi pagi ini.',
  sparklinePoints: [45, 52, 48, 58, 63, 61, 68, 71, 65, 72, 75, 78],
  sentimentBar: { positif: 71, netral: 19, negatif: 10 },
};

export const personaMock: PersonaMock = {
  name: 'Joko Widodo',
  role: 'Presiden Republik Indonesia',
  segment: 'Kepala Negara',
  region: 'Nasional',
  communicationStyle: 'Formal Hangat',
  tone: 'Empatik & Dekat',
  riskTolerance: 2,
  audiences: ['Pemilih grassroots Jawa-Bali', 'Kelas menengah urban', 'Komunitas digital milenial', 'Pebisnis dan investor', 'Pemimpin daerah'],
  team: [
    { name: 'Ari Santoso', role: 'Comms Director', initials: 'AS' },
    { name: 'Dewi Pratiwi', role: 'Digital Lead', initials: 'DP' },
    { name: 'Fajar Nugroho', role: 'Media Relations', initials: 'FN' },
  ],
  values: ['Integritas', 'Kerja Nyata', 'Merakyat', 'Transparansi', 'Kemandirian Bangsa'],
};

export const studioIssues: StudioIssue[] = [
  {
    id: 'dana-aspirasi',
    title: 'Kontroversi Dana Aspirasi DPR',
    tag: 'PANTAU',
    tagColor: '#B89455',
    platform: 'Twitter/X · TikTok',
    velocity: '+31% / jam',
    detected: '2 jam lalu',
    ewScore: 54,
    ewLevel: 'Pantau',
    responseIdeal: '3',
    scenarios: [
      {
        id: 's1',
        number: '01',
        name: 'Proaktif',
        desc: 'Tanggapi langsung, ambil kendali narasi.',
        draft: 'Saya memahami kekhawatiran masyarakat terkait transparansi penggunaan dana aspirasi. Sebagai bentuk komitmen akuntabilitas, kami akan mempublikasikan laporan penggunaan dana secara lengkap melalui portal resmi pemerintah dalam 48 jam ke depan. Setiap rupiah anggaran rakyat harus dapat dipertanggungjawabkan.',
        talkingPoints: [
          'Dana aspirasi dikelola melalui mekanisme APBN yang diawasi BPK dan KPK secara rutin.',
          'Laporan realisasi anggaran Q1 2026 telah diaudit dan tersedia di portal LPSE.',
          'Komitmen transparansi tercermin dalam peningkatan skor indeks antikorupsi 2025.',
        ],
        impact: { sentimen: '+14%', waktu: '6–12 jam', backfire: 'Rendah', platform: 'Twitter/X' },
      },
      {
        id: 's2',
        number: '02',
        name: 'Netral',
        desc: 'Akui tanpa memperkuat narasi negatif.',
        draft: 'Pertanyaan publik soal pengelolaan anggaran adalah hal yang sehat dalam demokrasi. Mekanisme pengawasan anggaran yang kuat sudah ada dan berjalan. Kami mengundang masyarakat untuk mengakses informasi lengkap melalui portal transparansi yang tersedia.',
        talkingPoints: [
          'Pengawasan anggaran dilakukan secara independen oleh lembaga yang berwenang.',
          'Informasi publik tersedia dan dapat diakses oleh siapa pun.',
          'Dialog konstruktif lebih produktif daripada narasi yang tidak berdasar fakta.',
        ],
        impact: { sentimen: '+6%', waktu: '12–24 jam', backfire: 'Sangat Rendah', platform: 'News · Web' },
      },
      {
        id: 's3',
        number: '03',
        name: 'Diam Strategis',
        desc: 'Biarkan mereda secara organik.',
        draft: '— Tidak ada pernyataan publik yang dikeluarkan. Tim monitoring aktif memantau perkembangan. Siapkan respons cadangan jika volume meningkat 50% dalam 4 jam ke depan. —',
        talkingPoints: [
          'Respons terlalu cepat dapat amplifikasi isu yang sedang menurun.',
          'Data menunjukkan isu serupa mereda dalam 36 jam tanpa intervensi.',
          'Prioritaskan komunikasi melalui jaringan kepercayaan, bukan platform publik.',
        ],
        impact: { sentimen: '+2%', waktu: '24–48 jam', backfire: 'Sedang', platform: 'Semua' },
      },
    ],
    circulating: [
      { text: '"Dana aspirasi seharusnya untuk rakyat, bukan formalitas."', direction: 'down' },
      { text: '"Transparansi anggaran sudah ada, kenapa masih dipertanyakan?"', direction: 'up' },
      { text: '"Ini bukan pertama kali isu seperti ini muncul sebelum pemilu."', direction: 'flat' },
    ],
    context: { origin: 'Akun @watchdog_id, 03.24 WIB', volume: '67.800 sebutan', dominantSentiment: 'Negatif (61%)', tokoh: 'Anies B., Fahri H.', precedent: 'Isu Dana BOS 2023 — mereda 48 jam' },
  },
  {
    id: 'tender',
    title: 'Tender Proyek Jalan Tol Kontroversi',
    tag: 'WASPADA',
    tagColor: '#CB102E',
    platform: 'News · Twitter/X',
    velocity: '+48% / jam',
    detected: '45 menit lalu',
    ewScore: 72,
    ewLevel: 'Kritis',
    responseIdeal: '1',
    scenarios: [
      {
        id: 's1',
        number: '01',
        name: 'Proaktif',
        desc: 'Klaim kendali narasi sebelum media bergerak.',
        draft: 'Terkait isu yang beredar mengenai proses tender proyek infrastruktur, saya tegaskan bahwa seluruh proses pengadaan mengikuti ketentuan Perpres No. 16 Tahun 2018 dengan pengawasan ketat LKPP. Investigasi internal segera dilakukan dan hasilnya akan diumumkan secara transparan.',
        talkingPoints: [
          'Proses tender dijalankan melalui LPSE dengan sistem e-procurement yang dapat ditelusuri.',
          'LKPP dan BPKP melakukan audit rutin pada setiap proyek di atas Rp 10 miliar.',
          'Tidak ada indikasi pelanggaran yang dikonfirmasi — investigasi dilakukan sebagai bentuk due diligence.',
        ],
        impact: { sentimen: '+18%', waktu: '4–8 jam', backfire: 'Sedang', platform: 'News · Twitter/X' },
      },
      {
        id: 's2',
        number: '02',
        name: 'Netral',
        desc: 'Percayakan pada proses hukum yang berjalan.',
        draft: 'Semua proses pengadaan pemerintah tunduk pada mekanisme pengawasan yang ketat. Jika terdapat dugaan pelanggaran, jalur hukum dan audit tersedia dan akan digunakan. Kami menghormati proses yang sedang berjalan.',
        talkingPoints: [
          'Mekanisme pengawasan pengadaan berjalan independen dari tekanan politik.',
          'Prasangka publik perlu dibedakan dari fakta yang telah terverifikasi.',
          'Komitmen kami pada tata kelola yang baik tidak berubah.',
        ],
        impact: { sentimen: '+8%', waktu: '12–18 jam', backfire: 'Rendah', platform: 'News' },
      },
      {
        id: 's3',
        number: '03',
        name: 'Diam Strategis',
        desc: 'Terlalu berisiko — tidak direkomendasikan.',
        draft: '— PERINGATAN: Diam strategis tidak disarankan untuk isu level Waspada dengan coverage media aktif. Risiko eskalasi sangat tinggi. Pertimbangkan Scenario 01 atau 02. —',
        talkingPoints: [
          'Media nasional sudah melakukan peliputan aktif — diam akan diartikan sebagai pengakuan.',
          'Waktu respons ideal sudah hampir lewat.',
          'Konsultasikan dengan tim hukum sebelum memutuskan.',
        ],
        impact: { sentimen: '-12%', waktu: '2–4 jam', backfire: 'Sangat Tinggi', platform: 'Semua' },
      },
    ],
    circulating: [
      { text: '"Siapa pemenang tender ini dan apa hubungannya dengan kekuasaan?"', direction: 'down' },
      { text: '"Infrastruktur tetap berjalan — yang penting hasilnya untuk rakyat."', direction: 'up' },
      { text: '"Masalah procurement lama yang tidak pernah tuntas."', direction: 'flat' },
    ],
    context: { origin: 'Investigasi Tempo.co, terbit 07.15 WIB', volume: '89.400 sebutan', dominantSentiment: 'Negatif (74%)', tokoh: 'KPK, Gerindra', precedent: 'Tender BUMN 2024 — EW Score 69, respons 2 jam' },
  },
  {
    id: 'kebijaksanaan-x',
    title: '#KebijaksanaanX Trending Nasional',
    tag: 'KRITIS',
    tagColor: '#CB102E',
    platform: 'Twitter/X · TikTok · News',
    velocity: '+89% / jam',
    detected: '18 menit lalu',
    ewScore: 87,
    ewLevel: 'Kritis',
    responseIdeal: '1',
    scenarios: [
      {
        id: 's1',
        number: '01',
        name: 'Proaktif',
        desc: 'Respons segera diperlukan — kuasai framing.',
        draft: 'Kepada seluruh masyarakat Indonesia: Saya mendengar kekhawatiran Anda. Kebijakan yang Anda pertanyakan dibuat dengan mempertimbangkan kepentingan jangka panjang bangsa. Dalam 2 jam, saya akan memberikan penjelasan langsung melalui konferensi pers. Transparansi adalah komitmen kami.',
        talkingPoints: [
          'Kebijakan ini telah melalui kajian 14 bulan melibatkan 200+ pakar dari 18 universitas.',
          'Dampak jangka pendek memang terasa berat, namun proyeksi 5 tahun menunjukkan manfaat yang signifikan.',
          'Kritik konstruktif adalah hak setiap warga negara — pemerintah siap berdialog.',
        ],
        impact: { sentimen: '+22%', waktu: '2–4 jam', backfire: 'Sedang-Tinggi', platform: 'Twitter/X · TV' },
      },
      {
        id: 's2',
        number: '02',
        name: 'Netral',
        desc: 'Jangan terlambat — netral masih memerlukan kecepatan.',
        draft: 'Pemerintah mencatat aspirasi yang disampaikan masyarakat terkait kebijakan terkini. Kami berkomitmen untuk membuka ruang dialog dan menyampaikan penjelasan yang komprehensif dalam forum yang tepat. Setiap suara rakyat adalah amanah yang kami emban.',
        talkingPoints: [
          'Dialogue dengan pemangku kepentingan sedang berlangsung.',
          'Kebijakan publik memerlukan waktu untuk dinilai dampak penuhnya.',
          'Kami terbuka terhadap masukan yang konstruktif dari semua pihak.',
        ],
        impact: { sentimen: '+10%', waktu: '6–12 jam', backfire: 'Sedang', platform: 'News · Web' },
      },
      {
        id: 's3',
        number: '03',
        name: 'Diam Strategis',
        desc: 'TIDAK DISARANKAN pada level Kritis ini.',
        draft: '— PERINGATAN KERAS: EW Score 87, trending #1 nasional, media nasional live coverage. Diam strategis akan memperkuat narasi bahwa pemerintah tidak peduli. Rekomendasi kuat: gunakan Scenario 01 dalam 45 menit ke depan. —',
        talkingPoints: [
          'Setiap menit diam dalam kondisi trending #1 = 8.000 cuitan tambahan.',
          'Tiga media nasional sudah konfirmasi akan tayang jam 19.00 WIB.',
          'Koalisi 12 tokoh oposisi sedang menyiapkan pernyataan bersama.',
        ],
        impact: { sentimen: '-28%', waktu: '1–2 jam', backfire: 'Kritis', platform: 'Semua' },
      },
    ],
    circulating: [
      { text: '"Kebijakan ini dibuat tanpa mendengar suara rakyat — inilah buktinya."', direction: 'down' },
      { text: '"Petisi sudah 180.000 tanda tangan dalam 3 jam. Rakyat tidak diam."', direction: 'down' },
      { text: '"Ada yang tidak kita ketahui tentang kebijakan ini."', direction: 'flat' },
    ],
    context: { origin: 'Akun oposisi, diperkuat 12 influencer, 06.42 WIB', volume: '240.000 cuitan', dominantSentiment: 'Negatif (82%)', tokoh: 'Refly H., Ade A., Ahmad D.', precedent: 'Krisis UU Omnibus 2020 — EW 91, respons 3 jam' },
  },
];
